# #####################################################
# LABO KALI - LAB1 - IMAGE CLIENT
# #####################################################
#
# Ce Dockerfile construit une image Docker du client légitime
# basée sur l'image de base
# Ajout de l'environnement de bureau XFCE accessible via RDP

ARG IMAGE_BASE

FROM ${IMAGE_BASE}

ARG USERNAME

# Installation des paquets
RUN apt update -q --fix-missing \
    && apt upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt -y install --no-install-recommends \
    dbus-x11 \
    xdg-utils \
    xinit \
    xorg \
    xorgxrdp \
    xrdp \
    xfce4 \
    xfce4-appfinder \
    xfce4-cpugraph-plugin:amd64 \
    xfce4-genmon-plugin:amd64 \
    xfce4-panel \
    xfce4-screenshooter \
    xfce4-session \
    xfce4-settings \
    xfce4-taskmanager \
    xfce4-whiskermenu-plugin:amd64 \
    xfce4-terminal \
    xfce4-power-manager \
    xfce4-power-manager-data \
    xfce4-power-manager-plugins \
    wireshark \
    firefox-esr \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    /var/log/alternatives.log \
    /var/log/apt/history.log \
    /var/log/apt/term.log \
    /var/log/dpkg.log \
    /tmp/* /var/tmp/*

# Configuration de la Timezone Europe/Paris et des locales 
RUN rm /etc/localtime \
    && ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && sed -i 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen \
    && echo 'LANG=${LANG}'>/etc/default/locale \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=${LANG}

# Activation de RDP
RUN systemctl enable xrdp.service

# Déclaration du port RDP
EXPOSE 3389/tcp

RUN adduser xrdp ssl-cert \
    && echo xfce4-session > /home/${USERNAME}/.xsession \
    && chown ${USERNAME}.${USERNAME} /home/${USERNAME}/.xsession \
    && chmod +x /home/${USERNAME}/.xsession

# Désactivation du paramètre Xfce Power Management qui contrôle la gestion de l'alimentation de l'affichage
RUN rm /etc/xdg/autostart/xfce4-power-manager.desktop \
    && if [ -e /etc/xdg/xfce4/panel/default.xml ] ; \
    then \
    sed -i s/power/fail/ /etc/xdg/xfce4/panel/default.xml ; \
    fi

# Autorisation pour wireshark (mais ne fonctionne pas)
# On est toujours obligé de faire un dpkg-reconfigure wireshark-common
RUN sudo groupadd -r wireshark \
    && usermod -a -G wireshark ${USERNAME} \
    && newgrp wireshark

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]