# #####################################################
# LABO KALI - LAB1 - IMAGE SERVEUR
# #####################################################
#
# Ce Dockerfile construit l'image du serveur 
# basée sur l'image de base
# Ajout du serveur DNS

ARG IMAGE_BASE

FROM ${IMAGE_BASE}

# Installation des paquets
RUN apt update -q --fix-missing \
    && apt upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt -y install --no-install-recommends \
    bind9 \
    bind9utils \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    /var/log/alternatives.log \
    /var/log/apt/history.log \
    /var/log/apt/term.log \
    /var/log/dpkg.log \
    /tmp/* /var/tmp/*

# Configuration du DNS
COPY config_dns/named.conf.local /etc/bind/
COPY config_dns/db.local.sio.fr /var/named/
COPY config_dns/db.192.168.56 /var/named/

RUN chgrp bind /etc/bind/named.conf.local \
    && chgrp bind /var/named/db.local.sio.fr \
    && chgrp bind /var/named/db.192.168.56

#Déclaration des ports exposés
EXPOSE 53/tcp
EXPOSE 53/udp

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]