#!/bin/bash

# Ports RDP port
RDP_PORT_CLIENT=13389
RDP_PORT_KALI=23389

# Ports SSH
SSH_PORT_SERVEUR=12222
SSH_PORT_CLIENT=22222
SSH_PORT_KALI=32222
SSH_PORT_ROUTEUR=42222

# Méta-paquets KALI
# Options: "arm" "core" "default" "everything" "firmware" "headless" "labs" "large" "nethunter"
# Défaut : core dans la LAB 1
KALI_PKG="core"

# Configuration du réseau
NOM_RESEAU="bridge_lab1"
# La configuration du DNS doit être modifiée si les valeurs ci-dessous sont modifiées
# Modifier la variable IP_RESEAU implique la suppression de tous les conteneurs et volumes associés
IP_RESEAU="192.168.56.0/24"
IP_SERVEUR="192.168.56.10"
IP_CLIENT="192.168.56.11"
IP_KALI="192.168.56.12"
IP_ROUTEUR="192.168.56.254"

# Configuration des noms d'hôtes
HOST_SERVEUR="srvssh"
HOST_CLIENT="clissh"
HOST_KALI="kali"
HOST_ROUTEUR="routeur"
HOST_BASE="basedebian"

# Configuration du domaine
DOMAINE=local.sio.fr

# Configuration de l'utilisateur
USERNAME="etusio"
USERPASS="Fghijkl1234*"

# Configuration des volumes
# Les volumes persistent les données du répertoire personnel
VOL_SERVEUR="home_serveur_lab1"
VOL_CLIENT="home_client_lab1"
VOL_KALI="home_kali_lab1"
VOL_ROUTEUR="home_routeur_lab1"

# ID docker HUB
ID_DOCKER=aporaf

# Nom de l'image
IMAGE_SERVEUR="$ID_DOCKER/serveurdebian12:lab1"
IMAGE_CLIENT="$ID_DOCKER/clientdebian12:lab1"
IMAGE_KALI="$ID_DOCKER/kalirolling:lab1"
IMAGE_ROUTEUR="$ID_DOCKER/routeurdebian12:lab1"
IMAGE_BASE=$ID_DOCKER/basedebian12:1.0

# Nom du conteneur
SERVEUR="serveur-lab1"
CLIENT="client-lab1"
KALI="kali-lab1"
ROUTEUR="routeur-lab1"
BASE="basedebian12"